// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG59zpgEr-YA8v9BrmYa_MqaO7AK_VpG0',
    appId: '1:619523222176:web:4336e671fc7c84276837c5',
    messagingSenderId: '619523222176',
    projectId: 'mentivisor-e43b3',
    authDomain: 'mentivisor-e43b3.firebaseapp.com',
    storageBucket: 'mentivisor-e43b3.firebasestorage.app',
    measurementId: 'G-0404JXBD4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD568Vhnlx6AyXzoWuhuseToSbYZLTXvio',
    appId: '1:619523222176:android:da57b8cf7cb71f246837c5',
    messagingSenderId: '619523222176',
    projectId: 'mentivisor-e43b3',
    storageBucket: 'mentivisor-e43b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjIUxwTFYScFdYF4gVCQJoECshyQtwShg',
    appId: '1:619523222176:ios:48456bbe2e4fd7686837c5',
    messagingSenderId: '619523222176',
    projectId: 'mentivisor-e43b3',
    storageBucket: 'mentivisor-e43b3.firebasestorage.app',
    iosBundleId: 'com.mentivisor.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjIUxwTFYScFdYF4gVCQJoECshyQtwShg',
    appId: '1:619523222176:ios:48456bbe2e4fd7686837c5',
    messagingSenderId: '619523222176',
    projectId: 'mentivisor-e43b3',
    storageBucket: 'mentivisor-e43b3.firebasestorage.app',
    iosBundleId: 'com.mentivisor.android',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG59zpgEr-YA8v9BrmYa_MqaO7AK_VpG0',
    appId: '1:619523222176:web:bdd60ea86d51df886837c5',
    messagingSenderId: '619523222176',
    projectId: 'mentivisor-e43b3',
    authDomain: 'mentivisor-e43b3.firebaseapp.com',
    storageBucket: 'mentivisor-e43b3.firebasestorage.app',
    measurementId: 'G-8YPSEQJ9QB',
  );
}
